"use client";

import { Copy, Download, Link2, LoaderCircle, Monitor, RefreshCw, ScanLine, Smartphone } from "lucide-react";
import QRImage from "@/components/qr-code";
import { formatSize, type Transfer } from "@/lib/shared";

export default function ConnectionCard({ inbox, origin, error, onRefresh, onCopy }: { inbox: Transfer | null; origin: string; error: string; onRefresh: () => void; onCopy: (value: string) => void }) {
  const url = inbox && origin ? `${origin}/r/${inbox.code}` : "";
  return <section className="connection-card"><div className="connection-decoration" aria-hidden="true"/><div className="connection-heading"><span className="connection-eyebrow"><span className="live-dot"/>اتصال سریع</span><button className="connection-refresh icon-button" onClick={onRefresh} aria-label="ساخت کد اتصال جدید" title="کد اتصال جدید"><RefreshCw size={16}/></button></div><h2>از گوشی به این دستگاه</h2><p className="connection-description">دوربین گوشی را روی کد بگیرید و متصل شوید.</p>
    {inbox?.status === "ready" ? <div className="inbox-ready"><div className="inbox-success-icon"><Download size={29}/></div><h3>فایل‌ها رسیدند!</h3><p>{inbox.fileCount.toLocaleString("fa-IR")} فایل · {formatSize(inbox.totalSize)}</p><a className="button button-white full-width" href={`/api/transfers/${inbox.code}/download`}><Download size={17}/>دریافت فایل‌ها</a><button className="connection-link" onClick={onRefresh}><RefreshCw size={15}/>دریافت جدید</button></div> : <><div className="qr-frame"><span className="qr-corner corner-tr"/><span className="qr-corner corner-tl"/><span className="qr-corner corner-br"/><span className="qr-corner corner-bl"/><QRImage value={url} size={132}/></div><div className="qr-caption"><ScanLine size={15}/><span>با دوربین گوشی اسکن کنید</span></div><div className="connection-divider"><span/>یا با کد اتصال<span/></div><div className="connection-code"><div dir="ltr" aria-label={`کد اتصال ${inbox?.code || ""}`}>{inbox ? inbox.code.split("").map((digit, index) => <span key={index}>{digit}</span>) : <span className="code-loading">••• •••</span>}</div><button className="icon-button" disabled={!inbox} onClick={() => inbox && onCopy(inbox.code)} aria-label="کپی کد اتصال"><Copy size={15}/></button></div>{error ? <button className="connection-link connection-error" onClick={onRefresh}>{error} · تلاش مجدد</button> : <button className="connection-link" onClick={() => onCopy(url)} disabled={!url}><Link2 size={15}/><span>کپی لینک ارسال از گوشی</span></button>}</>}
    <div className="connection-footer"><div className="connected-device-icons"><Smartphone size={13}/><span>↔</span><Monitor size={13}/></div><span>{inbox?.status === "pending" && inbox.fileCount > 0 ? <><LoaderCircle size={12} className="spin"/>در حال دریافت از گوشی…</> : "بدون نصب روی دستگاه دیگر"}</span></div>
  </section>;
}
