import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';

const base = process.env.TEST_URL || 'http://127.0.0.1:3000';
await mkdir('artifacts', { recursive: true });
const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] });
const desktop = await browser.newContext({ viewport: { width: 1440, height: 1000 }, permissions: ['clipboard-read', 'clipboard-write'] });
const page = await desktop.newPage();
const errors = [];
page.on('pageerror', (error) => errors.push(error.message));
await page.goto(base);
await page.waitForFunction(() => document.querySelector('.connection-code')?.textContent?.match(/\d{6}/));
await page.evaluate(() => document.fonts.ready);
await page.screenshot({ path: 'artifacts/desktop.png', fullPage: true });
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false);
await page.locator('input[type=file]').setInputFiles({ name: 'project-notes.txt', mimeType: 'text/plain', buffer: Buffer.from('A working file transfer from the browser.') });
await page.getByRole('button', { name: 'ارسال فایل‌ها', exact: false }).click();
await page.getByText('فایل‌ها با موفقیت ارسال شدند!').waitFor();
await page.locator('.share-actions').getByRole('button', { name: 'کپی لینک دریافت', exact: true }).click();
await page.getByRole('status').waitFor();
await page.screenshot({ path: 'artifacts/upload-success.png', fullPage: true });

const inboxResponse = await desktop.request.post(`${base}/api/transfers`, { data: { kind: 'inbox' } });
const inbox = await inboxResponse.json();
const phone = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
const phonePage = await phone.newPage();
await phonePage.goto(`${base}/r/${inbox.code}`);
await phonePage.getByText('به دستگاه مقصد متصل هستید').waitFor();
await phonePage.screenshot({ path: 'artifacts/phone-upload.png', fullPage: true });
assert.equal(await phonePage.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false);
await phonePage.locator('input[type=file]').setInputFiles({ name: 'from-android.txt', mimeType: 'text/plain', buffer: Buffer.from('Sent from the phone without installing or signing in.') });
await phonePage.getByRole('button', { name: 'ارسال فایل‌ها', exact: false }).click();
await phonePage.getByText('به همین راحتی، فایل‌ها رسیدند!').waitFor();
await page.getByText('فایل‌ها رسیدند!', { exact: true }).waitFor({ timeout: 15000 });
await page.locator('.main-nav').getByRole('button', { name: 'انتقال‌های من' }).click();
await page.getByPlaceholder('جست‌وجوی فایل یا کد…').fill('from-android');
await page.getByText('from-android.txt', { exact: true }).waitFor();
assert.equal(await page.locator('.history-row').count(), 1);
await page.getByPlaceholder('جست‌وجوی فایل یا کد…').fill('');
await page.screenshot({ path: 'artifacts/history.png', fullPage: true });
await page.locator('.secondary-nav').getByRole('button', { name: 'تنظیمات' }).click();
await page.getByLabel('نام دستگاه', { exact: true }).fill('کامپیوتر من');
await page.getByRole('button', { name: 'ذخیرهٔ تغییرات' }).click();
await page.locator('.sidebar-device').getByText('کامپیوتر من').waitFor();
await page.locator('.main-nav').getByRole('button', { name: 'راهنمای استفاده' }).click();
await page.getByText('طرف مقابل باید پُل را نصب کند؟', { exact: true }).click();
assert.equal(await page.locator('.faq-card details').first().getAttribute('open'), '');
await page.locator('.secondary-nav').getByRole('button', { name: 'بازخورد شما' }).click();
await page.getByLabel('پیام شما', { exact: true }).fill('آزمایش مرورگر: انتقال خیلی راحت انجام شد.');
await page.getByRole('button', { name: 'ارسال بازخورد', exact: true }).click();
await page.getByRole('status').getByText('ممنون! بازخورد شما ثبت شد.').waitFor();

const mobileHome = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
const mobilePage = await mobileHome.newPage();
await mobilePage.goto(base);
await mobilePage.waitForFunction(() => document.querySelector('.connection-code')?.textContent?.match(/\d{6}/));
await mobilePage.evaluate(() => document.fonts.ready);
await mobilePage.screenshot({ path: 'artifacts/mobile.png', fullPage: true });
assert.equal(await mobilePage.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false);
await mobilePage.getByRole('button', { name: 'باز کردن منو' }).click();
await mobilePage.locator('.main-nav').getByRole('button', { name: 'انتقال‌های من' }).click();
assert.equal(await mobilePage.locator('.sidebar-open').count(), 0);

const historyResponse = await desktop.request.get(`${base}/api/transfers`);
const history = await historyResponse.json();
const sentTransfer = history.transfers.find((item) => item.kind === 'send');
await phonePage.goto(`${base}/r/${sentTransfer.code}`);
await phonePage.getByText('فایل‌ها آمادهٔ دریافت‌اند').waitFor();
await phonePage.screenshot({ path: 'artifacts/phone-download.png', fullPage: true });
assert.equal(await phonePage.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false);
const download = await phone.request.get(`${base}/api/transfers/${sentTransfer.code}/download`);
assert.equal((await download.body()).toString(), 'A working file transfer from the browser.');
for (const item of history.transfers) await desktop.request.delete(`${base}/api/transfers/${item.code}`);
assert.deepEqual(errors, []);
await browser.close();
console.log('PASS: desktop upload, copy, phone pairing, receiver page, history search, settings, guide, feedback, mobile navigation, downloads, and no horizontal overflow.');
